version: 2
references:
  container_config: &container_config
    parallelism: 1
    docker:
    - image: circleci/node:8.11.3
      command: /sbin/init
    shell: /bin/bash --login
    working_directory: ~/KiiCorp/JavascriptStorageSDK
jobs:
  build:
    <<: *container_config
    steps:
    - checkout
    - run: echo 'export PATH=~/KiiCorp/JavascriptStorageSDK/scripts/:$PATH' >> $BASH_ENV
    - run: source testScript.sh

